/**
 * Shadows Character Sheet — the brand fonts, embedded.
 *
 * The app used to load Inter, Roboto Mono and Chakra Petch from Google Fonts.
 * Offline, which is how a GM's handed-over folder often runs, they fell back
 * to system fonts (audit C7). This writes src/styles/fonts.css instead: each
 * font's Latin subset as a WOFF2 data URI, so the stylesheet works from
 * file:// and inlines into the single-file build like any other, with no
 * network request and no CORS question.
 *
 * The WOFF2s come from Fontsource's npm packages (devDependencies), which are
 * the Google Fonts files, versioned. The generated CSS is committed; node_modules
 * is only needed to regenerate it. All three are SIL OFL 1.1: the licence
 * travels in the CSS header, so the built file carries it, and each package's
 * LICENSE is copied to src/styles/fonts/.
 *
 * Usage:  node tools/fonts.mjs   (npm run fonts)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT } from "./build.mjs";

export const OUT = "src/styles/fonts.css";
const LICENSES = "src/styles/fonts";

// Google's "latin" range, as Fontsource ships it. Anything outside it (→, ½)
// falls back per glyph to the next family in the stack, as it did before.
const LATIN = "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";

// The weights shadows.css and print.css use. Inter, Roboto Mono and Oxanium
// are variable (one file covers every weight); Chakra Petch isn't, so it's one
// file a weight. Oxanium is the big numbers' face (--numeric).
const FACES = [
  { family: "Inter", pkg: "@fontsource-variable/inter", file: "inter-latin-wght-normal.woff2", weight: "100 900" },
  { family: "Roboto Mono", pkg: "@fontsource-variable/roboto-mono", file: "roboto-mono-latin-wght-normal.woff2", weight: "100 700" },
  { family: "Oxanium", pkg: "@fontsource-variable/oxanium", file: "oxanium-latin-wght-normal.woff2", weight: "200 800" },
  ...[500, 600, 700].map(w => ({ family: "Chakra Petch", pkg: "@fontsource/chakra-petch", file: `chakra-petch-latin-${w}-normal.woff2`, weight: String(w) })),
];

const pkgDir = pkg => join(ROOT, "node_modules", pkg);

export function fontsCss() {
  const pkgs = [...new Set(FACES.map(f => f.pkg))];
  const licence = pkg => readFileSync(join(pkgDir(pkg), "LICENSE"), "utf8").replace(/\r\n?/g, "\n");
  // Each LICENSE opens with its copyright line, then the same OFL 1.1 text.
  const copyrights = pkgs.map(p => licence(p).split("\n")[0].replace(/\s+\S+\.ttf:.*$/, ""));
  const ofl = licence(pkgs[0]).split("\n").slice(1).join("\n").trim();
  for (const p of pkgs) {
    const body = licence(p).split("\n").slice(1).join("\n").trim();
    if (body !== ofl) throw new Error(`${p}'s LICENSE isn't the same OFL text as ${pkgs[0]}'s — check it before embedding`);
  }
  const faces = FACES.map(f => {
    const b64 = readFileSync(join(pkgDir(f.pkg), "files", f.file)).toString("base64");
    return `@font-face{font-family:"${f.family}";font-style:normal;font-display:swap;font-weight:${f.weight};` +
      `unicode-range:${LATIN};src:url(data:font/woff2;base64,${b64}) format("woff2")}`;
  });
  const versions = pkgs.map(p => `${p}@${JSON.parse(readFileSync(join(pkgDir(p), "package.json"), "utf8")).version}`);
  return `/* GENERATED by tools/fonts.mjs from ${versions.join(", ")}.
   Edit the generator, then run \`npm run fonts\`.

   The brand fonts, Latin subset, embedded so the app looks the same offline.

${copyrights.map(c => "   " + c).join("\n")}

${ofl.split("\n").map(l => ("   " + l).trimEnd()).join("\n")}
*/
${faces.join("\n")}
`;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const css = fontsCss();
  writeFileSync(join(ROOT, OUT), css);
  mkdirSync(join(ROOT, LICENSES), { recursive: true });
  for (const f of FACES) writeFileSync(join(ROOT, LICENSES, `${f.family.replace(/ /g, "")}-OFL.txt`),
    readFileSync(join(pkgDir(f.pkg), "LICENSE"), "utf8"));
  console.log(`wrote ${OUT}  (${(css.length / 1024).toFixed(0)} KB) and ${LICENSES}/`);
}
